# Generated by Django 3.2.5 on 2021-12-28 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='quest_text',
            new_name='question_text',
        ),
    ]
