# Generated by Django 3.2.5 on 2022-01-05 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_bulletin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bulletin',
        ),
    ]
